apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vellvista-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Adjust file size limit for uploads if necessary
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: vellvista.local
      http:
        paths:
          # Backend Routes
          - path: /trpc
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3001
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3001
          - path: /reviews
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3001
          - path: /product
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3001
          - path: /hero
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3001
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3001
          # Frontend routes
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
